version: '3'

services:
  nextjs:
    container_name: sf-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - backend_strapi

networks:
  backend_strapi:
    external: true
